### ISSUE TITLE
Code highlighting seems to be broken after latest update 20190613

### ISSUE THREAD

**Issue by 3ter** [gregorrr/anki-auto-markdown#11]
Hi there,

### Problem
I've updated the Add-on and I'm not getting line numbers and syntax highlighting anymore.
### Behavior to reproduce
* Add a new note and enter (it's highlighted in GitHub, of course you need ```C++ and ``` around)
```C++
#include <iostream>
int main()
{
  return 0
}
```
* Toggle Markdown (ctrl + m)
#### Expected
Syntax highlighting like above
#### Observed
No syntax highlighting and curiously even no line numbering
### Comments
I was just trying to put in a different style schema and disable the line numbering when it stopped working as expected. Other markdown features are still working.
### Steps I've taken to find out what's the issue
* I've downloaded the before latest version 20190430-auto_markdown.zip and found out, that syntax highlighting worked as expected

**Comment by gregorrr** [comment]
Thanks. I've just noticed this myself! Strange one. I'm on it

**Comment by gregorrr** [comment]
Any thoughts on this @JanSurft? Seems to be have happened after the refactor away from the global and to the `AnkiMarkdown` class. I can't see anything obvious that may be causing it.

**Comment by gregorrr** [comment]
Seems to have been caused by a change in `__init__.py` doing an import before adding the add-on directory to the path which caused `pygments` not to resolve correctly. I'll make another release today. Sorry about that; I need to do a more thorough test before making a release, especially since code snippets are the main reason I use this add-on!

Also, @3ter if you didn't find it already, you can change the colour scheme and whether or not to show line numbers in the config.

**Comment by 3ter** [comment]
@gregorrr It's the very same for me. Thanks for the explanation!
